from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session
from app.database import get_db
from app.models import User, FogLog, QRLog, ParkingSlot
from app.schemas import (
    QRVerifyRequest, QRVerifyResponse,
    VehicleExitRequest, VehicleExitResponse,
    FogStatusResponse, FogLogResponse, QRLogResponse
)
from app.auth import get_current_user, require_role
from app.services.fog_service import fog_service

router = APIRouter(prefix="/fog", tags=["Fog Computing Simulation"])

@router.post("/verify-qr", response_model=QRVerifyResponse)
def verify_qr(
    req: QRVerifyRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role(["STAFF", "ADMIN", "USER"]))
):
    """
    Simulated Fog Node edge endpoint:
    Processes QR authentication locally at the edge gateway.
    Validates token, vehicle match, slot availability, updates slot state,
    and synchronizes audit event to central cloud database.
    """
    result = fog_service.verify_and_process_qr(
        db=db,
        raw_qr_input=req.qr_token,
        scanned_vehicle_number=req.scanned_vehicle_number
    )
    return result

@router.post("/vehicle-exit", response_model=VehicleExitResponse)
def vehicle_exit(
    req: VehicleExitRequest,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role(["STAFF", "ADMIN"]))
):
    """
    Simulated edge gateway endpoint for vehicle departure:
    Transitions slot state from OCCUPIED back to AVAILABLE.
    Marks active reservation as COMPLETED and records exit timestamp.
    """
    res = fog_service.process_vehicle_exit(
        db=db,
        slot_id=req.slot_id,
        reservation_id=req.reservation_id
    )
    if not res.get("success"):
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=res.get("message"))
    return res

@router.get("/status", response_model=FogStatusResponse)
def get_fog_status(
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Real-time monitoring metrics from the local Fog Node."""
    return fog_service.get_fog_node_status(db=db)

@router.get("/logs", response_model=List[FogLogResponse])
def get_fog_logs(
    limit: int = 50,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role(["STAFF", "ADMIN"]))
):
    """Event log stream generated by local edge computation and sync operations."""
    return db.query(FogLog).order_by(FogLog.created_at.desc()).limit(limit).all()

@router.get("/qr-logs", response_model=List[QRLogResponse])
def get_qr_logs(
    limit: int = 50,
    db: Session = Depends(get_db),
    current_user: User = Depends(require_role(["STAFF", "ADMIN"]))
):
    """Complete audit table of every QR authentication attempt processed by the fog node."""
    logs = db.query(QRLog).order_by(QRLog.timestamp.desc()).limit(limit).all()
    results = []
    for l in logs:
        slot_code = l.slot.slot_code if l.slot else None
        results.append({
            "id": l.id,
            "reservation_id": l.reservation_id,
            "slot_id": l.slot_id,
            "slot_code": slot_code,
            "vehicle_number": l.vehicle_number,
            "verification_status": l.verification_status,
            "action": l.action,
            "fog_node": l.fog_node,
            "timestamp": l.timestamp,
            "details": l.details
        })
    return results
